#!/usr/bin/env python3
"""
drone-stack generator: read a stack (list of modules) + each module's manifest,
union their declared deps (arch-aware), and emit ONE Dockerfile + ONE compose file
for that stack. Driven by up.sh.

    python3 scripts/gen.py <stack> [--arch arm64|amd64]

Writes .build/<stack>/Dockerfile and .build/<stack>/compose.yml.
"""
import os, sys, argparse, yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_env(path):
    env = dict(os.environ)
    if os.path.isfile(path):
        for line in open(path):
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env.setdefault(k.strip(), v.split("#", 1)[0].strip())
    return env


def expand(s, env):
    out = s
    for k, v in env.items():
        out = out.replace("${%s}" % k, v).replace("$%s" % k, v)
    return out


def module_dir(path):
    return os.path.join(ROOT, "modules", path)


def load_module(path):
    f = os.path.join(module_dir(path), "module.yml")
    if not os.path.isfile(f):
        sys.exit("ERROR: module manifest not found: %s" % f)
    m = yaml.safe_load(open(f)) or {}
    m["_path"] = path
    return m


def resolve_order(stack_modules):
    """base first, then stack modules with their `needs` (deps before dependents)."""
    order, seen = [], set()

    def visit(path):
        if path in seen:
            return
        seen.add(path)
        m = load_module(path)
        for dep in (m.get("needs") or []):
            visit(dep)
        order.append(m)

    visit("base")
    for p in stack_modules:
        visit(p)
    return order


def arch_merged(deps, arch, kind):
    """deps.<kind> + deps.<arch>.<kind>, order-preserving, de-duped."""
    base = list((deps or {}).get(kind) or [])
    extra = list(((deps or {}).get(arch) or {}).get(kind) or [])
    out = []
    for x in base + extra:
        if x not in out:
            out.append(x)
    return out


def gen_dockerfile(mods, arch, env):
    base_mod = mods[0]
    bimg = (base_mod.get("base_image") or {}).get(arch)
    if not bimg:
        sys.exit("ERROR: base module declares no base_image for arch '%s'" % arch)

    L = []
    L.append("# GENERATED by scripts/gen.py — do not edit. Stack arch=%s" % arch)
    L.append("ARG TARGETARCH=%s" % arch)
    L.append("FROM %s" % bimg)
    L.append("ENV DEBIAN_FRONTEND=noninteractive LANG=C.UTF-8 TARGETARCH=%s" % arch)
    L.append('SHELL ["/bin/bash", "-c"]')
    # copy all module dirs so their install.sh scripts are available during RUN
    L.append("COPY modules/ /modules/")
    L.append("")

    for m in mods:
        path = m["_path"]
        deps = m.get("deps") or {}
        apt = arch_merged(deps, arch, "apt")
        pip = arch_merged(deps, arch, "pip")
        src = arch_merged(deps, arch, "source")
        for k, v in (m.get("env") or {}).items():
            L.append("ENV %s=%s" % (k, v))
        if not (apt or pip or src):
            continue
        L.append("# ---- module: %s (%s) ----" % (m.get("name", path), path))
        if apt:
            L.append("RUN apt-get update && apt-get install -y --no-install-recommends \\")
            L.append("      " + " ".join(apt) + " \\")
            L.append(" && rm -rf /var/lib/apt/lists/*")
        if pip:
            L.append("RUN python3 -m pip install --no-cache-dir \\")
            L.append("      " + " ".join('"%s"' % p for p in pip))
        for s in src:
            L.append("RUN TARGETARCH=%s bash /modules/%s/%s" % (arch, path, s))
        L.append("")
    return "\n".join(L) + "\n"


def gen_compose(mods, arch, stack, env):
    image = "drone-stack:%s" % stack
    mounts, runs = [], []
    for m in mods:
        for mt in (m.get("mounts") or []):
            mt = expand(mt, env)
            if mt not in mounts:
                mounts.append(mt)
        for r in (m.get("run") or []):
            runs.append("modules/%s/%s" % (m["_path"], r))
    doc = {
        "services": {
            "dev": {
                "image": image,
                "build": {
                    "context": "../..",
                    "dockerfile": ".build/%s/Dockerfile" % stack,
                },
                "container_name": "drone-stack-%s" % stack,
                "network_mode": "host",
                "privileged": True,
                "runtime": "nvidia" if arch == "arm64" else None,
                "working_dir": "/work",
                "volumes": ["../..:/work"] + mounts,
                "environment": [
                    "ROS_MASTER_URI=http://localhost:%s" % env.get("ROS_MASTER_PORT", "11399"),
                    "DISPLAY=${DISPLAY:-:0}",
                ],
                "command": ["sleep", "infinity"],
            }
        }
    }
    # drop None runtime (compose dislikes null)
    if doc["services"]["dev"]["runtime"] is None:
        del doc["services"]["dev"]["runtime"]
    header = "# GENERATED by scripts/gen.py. run scripts for this stack:\n#   " + \
             "\n#   ".join(runs) + "\n"
    return header + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("stack")
    ap.add_argument("--arch", default=None)
    a = ap.parse_args()

    env = load_env(os.path.join(ROOT, "config", "stack.env"))
    sf = os.path.join(ROOT, "stacks", a.stack + ".yml")
    if not os.path.isfile(sf):
        sys.exit("ERROR: stack not found: %s" % sf)
    stack = yaml.safe_load(open(sf)) or {}

    arches = stack.get("arch")
    arches = [arches] if isinstance(arches, str) else (arches or ["arm64"])
    arch = a.arch or arches[0]
    if arch not in arches:
        sys.exit("ERROR: arch %s not in stack's supported %s" % (arch, arches))

    mods = resolve_order(stack.get("modules") or [])
    outdir = os.path.join(ROOT, ".build", a.stack)
    os.makedirs(outdir, exist_ok=True)
    open(os.path.join(outdir, "Dockerfile"), "w").write(gen_dockerfile(mods, arch, env))
    open(os.path.join(outdir, "compose.yml"), "w").write(gen_compose(mods, arch, a.stack, env))
    open(os.path.join(outdir, "modules.txt"), "w").write("\n".join(m["_path"] for m in mods) + "\n")

    print("stack '%s' arch=%s  modules: %s" % (a.stack, arch, ", ".join(m["_path"] for m in mods)))
    print("  -> %s/Dockerfile" % outdir)
    print("  -> %s/compose.yml" % outdir)


if __name__ == "__main__":
    main()
